import Link from 'next/link';
import { PendingButton } from './pending-button';
import { configured, requireGoogleAdmin } from '@/lib/google/server';
import { synchronize, importAllContacts } from './actions';
export const maxDuration=60;
export default async function GoogleContacts({searchParams}:{searchParams:Promise<{status?:string;import?:string}>}) {
  const {supabase}=await requireGoogleAdmin();const {data:state}=await supabase.from('google_sync_state').select('connected_email,last_synced_at,last_status,last_error').eq('id',true).maybeSingle();const {status,import:importMessage}=await searchParams;
  return <><div className="page-heading"><div><h1>Google Contacts</h1><p>Nombre, apellidos, correo y teléfono en ambas direcciones. El estado de la app se refleja mediante etiquetas en Google.</p></div></div><section className="card member-form"><h2>Cuenta del sindicato</h2><p>directiva@sindicato2bancobice.cl</p>{!configured()?<p>La conexión está pendiente de configuración. Aún no se enviaron contactos a Google.</p>:<Link className="button" href="/api/google/connect">{state?.connected_email?'Volver a conectar Google':'Conectar Google'}</Link>}{status==='conflicts'&&<p className="error-banner">La sincronización terminó con contactos pendientes. Revisa el detalle a continuación.</p>}{status==='success'&&<p className="success-banner">Sincronización completada.</p>}{status==='authorization_failed'&&<p className="error-banner">No se pudo autorizar. Elige la cuenta del sindicato y permite el acceso a contactos.</p>}{state?.connected_email&&<><p>Conectada: {state.connected_email}</p><form action={synchronize}><PendingButton label="Sincronizar ahora" pendingLabel="Sincronizando…"/></form></>}<p>Sincronización automática: una vez al día. Puedes usar Sincronizar ahora para adelantarla.</p><p>Última sincronización: {state?.last_synced_at?new Date(state.last_synced_at).toLocaleString('es-CL',{timeZone:'America/Santiago'}):'Todavía no realizada'}</p>{state?.last_error&&<pre style={{whiteSpace:'pre-wrap'}}>{state.last_error}</pre>}{importMessage&&<p role="status">{importMessage}</p>}{state?.connected_email&&<section><h2>Importar socios desde Google</h2><p>Importa todos los contactos de esta cuenta como socios activos, en lotes de 25. Repite hasta que no queden pendientes. Los posibles duplicados se conservan para revisión.</p><form action={importAllContacts}><PendingButton label="Importar próximos 25 socios" pendingLabel="Importando socios…"/></form><Link href="/panel/personas">Ver y editar fichas importadas</Link></section>}<p>Etiquetas de estado: Sindicato 2 · Socio activo, Sindicato 2 · Adherente y Sindicato 2 · Inactivo. Cambia el estado en la ficha de la app; al sincronizar se reemplaza su etiqueta sindical y se conservan las demás. Los inactivos también se sincronizan y mantienen su contacto. Cambiar una etiqueta en Google no cambia el estado de la app.</p><p>Las fichas nuevas tienen un identificador propio en Google. También se pueden reutilizar contactos sin vínculo cuyos datos coincidan. Los contactos de Google sin ficha no se registran automáticamente como socios. Los datos laborales y sindicales permanecen en la app. Las fichas eliminadas desde la app se borran de Google en la próxima sincronización. Las bajas confirmadas en Google eliminan también la ficha de la app. Cuando Google devuelve una nueva identidad tras una fusión, se conserva la ficha sobreviviente y se retira la duplicada. Los cambios simultáneos en un mismo campo requieren revisión.</p></section></>;
}
