import Link from 'next/link';
import { PendingButton } from './pending-button';
import { configured, requireGoogleAdmin } from '@/lib/google/server';
import { synchronize, importAllContacts } from './actions';
export const maxDuration=60;
export default async function GoogleContacts({searchParams}:{searchParams:Promise<{status?:string;import?:string}>}) {
  const {supabase}=await requireGoogleAdmin();const {data:state}=await supabase.from('google_sync_state').select('connected_email,last_synced_at,last_status,last_error').eq('id',true).maybeSingle();const {status,import:importMessage}=await searchParams;
  return <><div className="page-heading"><div><h1>Google Contacts</h1><p>Nombre, apellidos, correo y teléfono en ambas direcciones.</p></div></div><section className="card member-form"><h2>Cuenta del sindicato</h2><p>directiva@sindicato2bancobice.cl</p>{!configured()?<p>La conexión está pendiente de configuración. Aún no se enviaron contactos a Google.</p>:<Link className="button" href="/api/google/connect">{state?.connected_email?'Volver a conectar Google':'Conectar Google'}</Link>}{status==='authorization_failed'&&<p className="error-banner">No se pudo autorizar. Elige la cuenta del sindicato y permite el acceso a contactos.</p>}{state?.connected_email&&<><p>Conectada: {state.connected_email}</p><form action={synchronize}><PendingButton label="Sincronizar ahora" pendingLabel="Sincronizando…"/></form></>}<p>Última sincronización: {state?.last_synced_at?new Date(state.last_synced_at).toLocaleString('es-CL',{timeZone:'America/Santiago'}):'Todavía no realizada'}</p>{state?.last_error&&<pre style={{whiteSpace:'pre-wrap'}}>{state.last_error}</pre>}{importMessage&&<p role="status">{importMessage}</p>}{state?.connected_email&&<section><h2>Importar socios desde Google</h2><p>Importa todos los contactos de esta cuenta como socios activos, en lotes de 25. Repite hasta que no queden pendientes. Los posibles duplicados se conservan para revisión.</p><form action={importAllContacts}><PendingButton label="Importar próximos 25 socios" pendingLabel="Importando socios…"/></form><Link href="/panel/personas">Ver y editar fichas importadas</Link></section>}<p>La sincronización vincula las fichas existentes por correo. Los contactos de Google sin ficha no se registran automáticamente como socios. Los datos laborales y sindicales permanecen en la app. Las eliminaciones y los cambios simultáneos se conservan para revisión.</p></section></>;
}
